# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/

version: 2

jobs:
  ssh-connection:
    docker:
      - image: praqma/network-multitool
    steps:
      - run: mkdir ~/.ssh ; ssh-keyscan web.witpass.co.uk > ~/.ssh/known_hosts
      - run: echo ${CI_SSH_PRIVATE_KEY} | base64 -d  > ~/.ssh/witpass_web_server_ci_key; chmod go-rwx -R ~/.ssh 
      - run: ssh -i ~/.ssh/witpass_web_server_ci_key  witpass@web.witpass.co.uk uptime
  list-docker-containers:
    docker:
      - image: praqma/network-multitool
    steps:
      - run: ssh -i ~/.ssh/witpass_web_server_ci_key  witpass@web.witpass.co.uk docker ps


workflows:
  version: 2
  connect-and-deploy:
    jobs:
      - ssh-connection
      - list-docker-containers
