# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2

jobs:
  ssh-connection:
    docker:
      - image: praqma/network-multitool
    steps:
      - run: echo ${CI_SSH_PRIVATE_KEY} > ~/.ssh/witpass_web_server_ci_key
      - run: ssh -i ~/.ssh/witpass_web_server_ci_key  root@web.witpass.co.uk uptime

workflows:
  version: 2
  connect-and-deploy:
    jobs:
      - ssh-connection
